//! Writes tests/c/fixture.h: a small JPEG as a C array, for tests/c/smoke.c, which has no encoder
//! of its own to make one with. Run it again only when the fixture should change:
//!
//!   cargo run --example make_fixture > tests/c/fixture.h

use image::codecs::jpeg::JpegEncoder;
use image::{Rgb, RgbImage};

fn main() {
    let picture = RgbImage::from_fn(16, 8, |x, y| Rgb([(x * 16) as u8, (y * 32) as u8, 128]));
    let mut jpeg = Vec::new();
    picture
        .write_with_encoder(JpegEncoder::new_with_quality(&mut jpeg, 80))
        .unwrap();

    println!("/* Generated by examples/make_fixture.rs: a 16 x 8 JPEG. */");
    println!("#define FIXTURE_WIDTH 16");
    println!("#define FIXTURE_HEIGHT 8");
    println!("static const unsigned char fixture_jpeg[] = {{");
    for line in jpeg.chunks(16) {
        let bytes: Vec<String> = line.iter().map(|b| format!("0x{b:02x}")).collect();
        println!("    {},", bytes.join(", "));
    }
    println!("}};");
}
